name: 'Config Patch'
type: module
description: 'Create patches from configuration diffs'
core_version_requirement: ^9 || ^10
package: 'Config'
configure: config_patch.settings

# Information added by Drupal.org packaging script on 2022-11-07
version: '3.0.2'
project: 'config_patch'
datestamp: 1667833243
